import type { Metadata } from "next";
import { GoogleAnalytics } from "@next/third-parties/google";

import { Inter } from "next/font/google";

import "../globals.css";
import AuthProvider from "@/components/Auth/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Graph",
  description: "Graph generated by Notion Graph by Ac. Junior",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body data-layout="graph">
        <AuthProvider>{children}</AuthProvider>
        {process.env.NODE_ENV === "production" && (
          <GoogleAnalytics gaId="G-LX2KQTDYSV" />
        )}
      </body>
    </html>
  );
}
