import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react"

import "../globals.css";
import AuthProvider from "@/components/Auth/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Graph",
  description: "Graph generated by Notion Graph by Ac. Junior",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body data-layout="graph">
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
